# compiler and the flag options
CC = gcc
CFLAGS = -Wall

# object names
OBJ = stack.o teststack.o

# final executable name
all: stack

# compiling command
use_linked_list:	$(OBJ)
					$(CC) $(CFLAGS) -o
					teststack $(OBJ)

# declaring and definition files
teststack.o: stac.h stack.c

# deleting all object files and the executable
clean:
	rm -f teststack *.o
	rm -f teststack
